server:
  servlet:
    context-path: /
  port: 80

security:
  cas:
    server:
      base-url: http://localhost:8080/cas
    service:
      base-url: http://localhost
#      resolution-mode: dynamic
#cas:
#  client-host-url: http://localhost/login
#  server-login-url: http://localhost:8080/cas
#  server-url-prefix: http://localhost:8080/cas
#  validation-type: cas3
